### ISSUE TITLE
Had to disable Y button in running the intake ... need to figure out how to get around that.

### ISSUE THREAD

**Issue by Canthv0** [Canthv0/Trex#30]

**Comment by DarthRacer** [comment]
Discussed intake setup as follows:
Run intake roller independent of magazine. Roller is on/off with button.
Make magazine rollers run in normal direction with a button push. (no smacna)
Make entire intake system run in reverse with a button push. To clear jams.

**Comment by Canthv0** [comment]
Automatic intake has been implemented:

* Turn on intake mode
*  Intake rollers + belt spin
*  When magazine sensor sees the ball runs magazine belt till the ball is clear of the sensor
*  Repeat each time a ball comes in until the shooter sensor detect a ball then turn off intake mode
